/**
 * This file was generated by the JPA Modeler
 */ 

package domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.FormParam;

/**
 * @author jGauravGupta
 */

@Entity
public class Person { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @FormParam("id2")
    private Long id2;

    @Basic
    @FormParam("firstName")
    private String firstName;

    @Basic
    @FormParam("lastName")
    private String lastName;


    public Long getId2() {
        return this.id2;
    }

    public void setId2(Long id2) {
        this.id2 = id2;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


}
